import { describe, expect, it } from 'vitest';
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { MEASURED_FROM_SHA256 } from '@sudobility/music_player/rn/expression-table';

/**
 * Two sets of audio assets are *derived* from this app's soundfont:
 *
 * - `public/audio/percussion/` — the eight GM drum kits, rendered by
 *   `music_io/scripts/build-percussion-packs.mjs`, because no CDN publishes
 *   usably-licensed GM percussion.
 * - `music_io`'s expression table — the per-instrument velocity curves, filter
 *   corners, release times and sustain flags, measured by
 *   `music_io/scripts/measure-expression.mjs`.
 *
 * Neither is regenerated by any build. Replace `FluidR3Mono_GM.sf3` — a newer
 * MuseScore release, a different font entirely — and React Native goes on
 * playing drums and shaping notes from the *old* one, with nothing anywhere
 * reporting a problem. It would present as "RN sounds subtly unlike web",
 * which is exactly the complaint that is hardest to trace.
 *
 * The guard lives here rather than in music_io because this app owns the font;
 * music_io has no copy to hash. The hash comes from a dependency-free subpath
 * rather than the RN entry, which would drag in optional peers a web app does
 * not install.
 *
 * If this fails, regenerate both — see `docs/` or the script headers:
 *
 *   cd ../music_io
 *   node scripts/measure-expression.mjs --soundfont ../music_app/public/audio/FluidR3Mono_GM.sf3 \
 *     --out src/rn/playback/expression-table.ts
 *   node scripts/build-percussion-packs.mjs --soundfont ../music_app/public/audio/FluidR3Mono_GM.sf3 \
 *     --out ../music_app/public/audio/percussion
 */
const SOUNDFONT = 'public/audio/FluidR3Mono_GM.sf3';
const PERCUSSION_MANIFEST = 'public/audio/percussion/names.json';

function soundfontHash(): string {
  return createHash('sha256').update(readFileSync(SOUNDFONT)).digest('hex');
}

describe('generated audio assets match the soundfont they came from', () => {
  it('the expression table was measured from this font', () => {
    expect(MEASURED_FROM_SHA256).toBe(soundfontHash());
  });

  it('the percussion packs were rendered from this font', () => {
    const manifest = JSON.parse(readFileSync(PERCUSSION_MANIFEST, 'utf8')) as {
      soundfontSha256: string;
      packs: string[];
    };
    expect(manifest.soundfontSha256).toBe(soundfontHash());
  });

  it('ships a pack for every General MIDI drum kit', () => {
    // Eight kits, and a missing one is a silent percussion track rather than an
    // error — the engine resolves any program to a kit and then finds no pack.
    const manifest = JSON.parse(readFileSync(PERCUSSION_MANIFEST, 'utf8')) as { packs: string[] };
    expect(manifest.packs).toEqual([
      'percussion_0',
      'percussion_8',
      'percussion_16',
      'percussion_24',
      'percussion_25',
      'percussion_32',
      'percussion_40',
      'percussion_48',
    ]);
    for (const pack of manifest.packs) {
      expect(() => readFileSync(`public/audio/percussion/${pack}-mp3.js`), pack).not.toThrow();
    }
  });
});
